cabal-version: 3.0
name:          tree-sitter
version:       0.1.0.0
synopsis:      Haskell bindings to libtree-sitter
license:       NONE
build-type:    Simple
extra-source-files:
  cbits/ts/include/tree_sitter/api.h
  cbits/ts/src/alloc.c
  cbits/ts/src/alloc.h
  cbits/ts/src/array.h
  cbits/ts/src/atomic.h
  cbits/ts/src/clock.h
  cbits/ts/src/error_costs.h
  cbits/ts/src/get_changed_ranges.c
  cbits/ts/src/get_changed_ranges.h
  cbits/ts/src/host.h
  cbits/ts/src/language.c
  cbits/ts/src/language.h
  cbits/ts/src/length.h
  cbits/ts/src/lexer.c
  cbits/ts/src/lexer.h
  cbits/ts/src/node.c
  cbits/ts/src/parser.c
  cbits/ts/src/parser.h
  cbits/ts/src/point.h
  cbits/ts/src/query.c
  cbits/ts/src/reduce_action.h
  cbits/ts/src/reusable_node.h
  cbits/ts/src/stack.c
  cbits/ts/src/stack.h
  cbits/ts/src/subtree.c
  cbits/ts/src/subtree.h
  cbits/ts/src/tree.c
  cbits/ts/src/tree.h
  cbits/ts/src/tree_cursor.c
  cbits/ts/src/tree_cursor.h
  cbits/ts/src/ts_assert.h
  cbits/ts/src/unicode.h
  cbits/ts/src/unicode/ptypes.h
  cbits/ts/src/unicode/umachine.h
  cbits/ts/src/unicode/urename.h
  cbits/ts/src/unicode/utf.h
  cbits/ts/src/unicode/utf16.h
  cbits/ts/src/unicode/utf8.h
  cbits/ts/src/wasm/stdlib.c
  cbits/ts/src/wasm/wasm-stdlib.h
  cbits/ts/src/wasm_store.c
  cbits/ts/src/wasm_store.h

common shared
  default-language: GHC2021
  default-extensions:
    OverloadedStrings
    DerivingStrategies
    StrictData
  ghc-options: -Wall -Wunused-packages

library
  import:         shared
  hs-source-dirs: src
  exposed-modules:
    TreeSitter
    TreeSitter.Language
    TreeSitter.Node
    TreeSitter.Parser
    TreeSitter.Query
  other-modules:
    TreeSitter.FFI
  build-depends:
      base >= 4.18 && < 5
    , bytestring
    , text
    , unix
  c-sources:
    cbits/tree_sitter_shim.c
    cbits/ts/src/lib.c
  include-dirs:
    cbits/ts/include
    cbits/ts/src
