cabal-version: 3.0
name:          tree-sitter
version:       0.1.0.0
synopsis:      Haskell bindings to libtree-sitter
license:       NONE
build-type:    Simple

common shared
  default-language: GHC2021
  default-extensions:
    OverloadedStrings
    DerivingStrategies
    StrictData
  ghc-options: -Wall -Wunused-packages

library
  import:         shared
  hs-source-dirs: src
  exposed-modules:
    TreeSitter
    TreeSitter.Language
    TreeSitter.Node
    TreeSitter.Parser
    TreeSitter.Query
  other-modules:
    TreeSitter.FFI
  build-depends:
      base >= 4.18 && < 5
    , bytestring
    , text
    , unix
  c-sources:
    cbits/tree_sitter_shim.c
    cbits/ts/src/lib.c
  include-dirs:
    cbits/ts/include
    cbits/ts/src
