module CodeStar.Config.Migrate
  ( migrateJsonToToml
  ) where

import Data.ByteString qualified as BS
import Data.Text (Text)
import Data.Text qualified as Text
import Data.Text.IO qualified as Text.IO
import System.Directory (doesFileExist)
import System.FilePath ((</>))
import System.IO (hPutStrLn, stderr)

import CodeStar.Config.Json (parseJsonConfig)
import CodeStar.Config.Paths qualified as Paths
import CodeStar.Config.Types
import CodeStar.Config.Defaults (defaultConfig)

migrateJsonToToml :: Maybe FilePath -> IO ()
migrateJsonToToml mWorkspace = do
  globalDir <- Paths.globalConfigDir
  let projDir = Paths.projectDir (maybe "." id mWorkspace)

  migrateFile globalDir
  migrateFile projDir

migrateFile :: FilePath -> IO ()
migrateFile dir = do
  let jsonPath = dir </> "settings.json"
      tomlPath = dir </> "settings.toml"
  jsonExists <- doesFileExist jsonPath
  tomlExists <- doesFileExist tomlPath
  if not jsonExists
    then hPutStrLn stderr $ "  [skip] " <> jsonPath <> " (not found)"
    else if tomlExists
      then hPutStrLn stderr $ "  [skip] " <> tomlPath <> " already exists"
      else do
        contents <- BS.readFile jsonPath
        case parseJsonConfig contents of
          Left err -> hPutStrLn stderr $ "  [error] " <> jsonPath <> ": " <> Text.unpack err
          Right _partial -> do
            Text.IO.writeFile tomlPath (generateTomlTemplate defaultConfig)
            hPutStrLn stderr $ "  [ok] " <> tomlPath <> " created (default template)"
            hPutStrLn stderr $ "       Review and customize, then delete " <> jsonPath

generateTomlTemplate :: Config -> Text
generateTomlTemplate cfg = Text.unlines
  [ "# CodeStar configuration"
  , "# Generated by: codestar migrate-config"
  , ""
  , "[server]"
  , "port = " <> tshow cfg.server.port
  , "host = " <> quote cfg.server.host
  , "http_timeout = " <> tshow cfg.server.httpTimeout
  , "graceful_shutdown_timeout = " <> tshow cfg.server.gracefulShutdownTimeout
  , "ping_interval = " <> tshow cfg.server.pingInterval
  , ""
  , "[telemetry]"
  , "mode = " <> quote (telemetryModeText cfg.telemetry.mode)
  , "service_name = " <> quote cfg.telemetry.serviceName
  , "log_to_stderr = " <> boolText cfg.telemetry.logToStderr
  , "metrics_enabled = " <> boolText cfg.telemetry.metricsEnabled
  , "metrics_bind_host = " <> quote cfg.telemetry.metricsBindHost
  , maybe "" (\p -> "metrics_port = " <> tshow p) cfg.telemetry.metricsPort
  , ""
  , "[context]"
  , "max_tokens = " <> tshow cfg.context.maxTokens
  , "repo_map_reserve = " <> tshow cfg.context.repoMapReserve
  , "memory_reserve = " <> tshow cfg.context.memoryReserve
  , "compaction_reserve = " <> tshow cfg.context.compactionReserve
  , "response_reserve = " <> tshow cfg.context.responseReserve
  , ""
  , "[compaction]"
  , "trigger_fraction = " <> tshow cfg.compaction.triggerFraction
  , "max_context_tokens = " <> tshow cfg.compaction.maxContextTokens
  , ""
  , "[shell]"
  , "default_timeout = " <> tshow cfg.shell.defaultTimeout
  , "max_concurrent = " <> tshow cfg.shell.maxConcurrent
  , "output_truncation = " <> tshow cfg.shell.outputTruncation
  , ""
  , "[session]"
  , "max_per_user = " <> tshow cfg.session.maxPerUser
  , "inactivity_timeout = " <> tshow cfg.session.inactivityTimeout
  , ""
  , "[budget]"
  , "max_steps = " <> tshow cfg.budgets.maxSteps
  , ""
  , "[repomap]"
  , "rebuild_interval_ms = " <> tshow cfg.repomap.rebuildIntervalMs
  , "max_tokens = " <> tshow cfg.repomap.rmMaxTokens
  , "batch_size = " <> tshow cfg.repomap.batchSize
  , ""
  , "[memory]"
  , "enabled = " <> boolText cfg.memory.enabled
  , "max_entries = " <> tshow cfg.memory.maxEntries
  , "auto_discover = " <> boolText cfg.memory.autoDiscover
  ]

telemetryModeText :: TelemetryMode -> Text
telemetryModeText TelemetryOtlp = "otlp"
telemetryModeText TelemetryStderr = "stderr"
telemetryModeText TelemetryOff = "off"

tshow :: Show a => a -> Text
tshow = Text.pack . show

quote :: Text -> Text
quote t = "\"" <> t <> "\""

boolText :: Bool -> Text
boolText True = "true"
boolText False = "false"
