{- |
= CLI.Diagnostics — startup health checks

Prints diagnostic information during CLI startup so the user can quickly
spot configuration problems before the agent starts.  Two checks are
performed:

  * __Grammar diagnostics__: verifies that Tree-sitter grammar libraries
    were found and loaded.  Without grammars, the repo-map extractor
    cannot parse source files and falls back to an empty map, which
    significantly reduces the LLM's codebase awareness.

  * __Stale fingerprint safety rail__: detects cache entries from a
    previous extractor version.  These are silently ignored at runtime;
    this check surfaces them so the user knows to run @cache-gc --delete@.

Both checks are informational only — the agent runs even if they report
problems.
-}
module CLI.Diagnostics
  ( printGrammarDiagnostics
  , printStaleFingerprintSafetyRail
  ) where

import Data.Map.Strict qualified as Map
import Data.Text (Text)
import Data.Text qualified as Text
import Data.Text.IO qualified as Text.IO

import CodeStar.RepoMap.CacheGc (CacheGcReport (..), StaleReason (..), runCacheGc)
import CodeStar.Storage (StorageBackend)
import CodeStar.TreeSitter.Grammars (knownGrammars)

-- | Print the grammar directory path, the number of loaded grammars, and
-- any warnings generated by 'grammarWarnings'.
-- Called once at startup in "CLI.Setup".
printGrammarDiagnostics :: FilePath -> Int -> IO ()
printGrammarDiagnostics grammarDir loadedCount = do
  Text.IO.putStrLn ("Grammars dir: " <> Text.pack grammarDir)
  Text.IO.putStrLn ("Grammars loaded: " <> tshow loadedCount <> " / " <> tshow (length knownGrammars))
  mapM_ (Text.IO.putStrLn . Text.pack) (grammarWarnings grammarDir loadedCount)

grammarWarnings :: FilePath -> Int -> [String]
grammarWarnings grammarDir loadedCount
  | loadedCount == 0 =
      [ "WARNING: no grammars loaded. Repo-map extraction will skip supported files."
      , "  Remediation: run `codestar-cli fetch-grammars`."
      , "  Verify this path contains grammar libraries: " <> grammarDir
      , "  If this path is unexpected, check your XDG data directory env configuration."
      ]
  | loadedCount < max 3 (length knownGrammars `div` 4) =
      [ "WARNING: grammar load count is unexpectedly low."
      , "  Remediation: run `codestar-cli fetch-grammars` for missing languages."
      , "  Verify this path points to the grammar directory you expect: " <> grammarDir
      ]
  | otherwise = []

-- | Detect and report stale repo-map cache entries.
--
-- A __stale-global__ entry was written by a different extractor or query
-- version; __stale-both__ means both the global fingerprint and the file
-- fingerprint are stale.  Either kind is safe to delete.
--
-- This is called "safety rail" because it prevents silent cache
-- misses that would look like slow or wrong repo-map results.
printStaleFingerprintSafetyRail :: StorageBackend -> Maybe FilePath -> IO ()
printStaleFingerprintSafetyRail cacheBackend mWorkspace = do
  gcReport <- runCacheGc cacheBackend mWorkspace False
  let staleGlobal = Map.findWithDefault 0 StaleGlobal gcReport.staleByReason
      staleBoth   = Map.findWithDefault 0 StaleBoth   gcReport.staleByReason
      staleFingerprint = staleGlobal + staleBoth
  if staleFingerprint > 0
    then
      Text.IO.putStrLn
        ( "Note: detected "
            <> tshow staleFingerprint
            <> " stale repo-map cache entries from a previous extractor/query fingerprint; these entries are ignored. "
            <> "Run `codestar-cli cache-gc --delete` to clean them."
        )
    else pure ()

tshow :: Show a => a -> Text
tshow = Text.pack . show
